# Generated by Django 6.1 on 2026-09-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
